INSERT INTO REPORT(NUMBER_REPORT, DESCRIPTION) VALUES(1, 'Test');
INSERT INTO REPORT(NUMBER_REPORT, DESCRIPTION) VALUES(2, 'Exam');
INSERT INTO REPORT(NUMBER_REPORT, DESCRIPTION) VALUES(3, 'No report');

--SELECT * FROM REPORT;

INSERT INTO SUBJECT(NAME, HOURS) VALUES('Criptography', 126);
INSERT INTO SUBJECT(NAME, HOURS) VALUES('Programming', 120);
INSERT INTO SUBJECT(NAME, HOURS) VALUES('Math', 140);
INSERT INTO SUBJECT(NAME, HOURS) VALUES('ISO', 60);

--SELECT * FROM SUBJECT;

INSERT INTO SEMESTER(NUMBER_SEMESTER, DESCRIPTION) VALUES(1, 'WINTER');
INSERT INTO SEMESTER(NUMBER_SEMESTER, DESCRIPTION) VALUES(2, 'SUMMER');
INSERT INTO SEMESTER(NUMBER_SEMESTER, DESCRIPTION) VALUES(3, 'WINTER');
INSERT INTO SEMESTER(NUMBER_SEMESTER, DESCRIPTION) VALUES(4, 'SUMMER');

--SELECT * FROM SEMESTER;

INSERT INTO STUDENT(FIRST_NAME, LAST_NAME, SEMESTER_NUMBER) VALUES( 'Alex', 'Wong', 1);
INSERT INTO STUDENT(FIRST_NAME, LAST_NAME, SEMESTER_NUMBER) VALUES( 'Jim', 'Smith', 1);
INSERT INTO STUDENT(FIRST_NAME, LAST_NAME, SEMESTER_NUMBER) VALUES( 'Bob', 'Andersen', 1);
INSERT INTO STUDENT(FIRST_NAME, LAST_NAME, SEMESTER_NUMBER) VALUES( 'Alex', 'Smith', 1);

--SELECT * FROM STUDENT;

INSERT INTO PASSING(DATE_EXAM, MARK, STUDENT_NUMBER_OF_BOOK, SUBJECT_NAME) 
    VALUES( to_date('14-03-2018', 'dd-mm-yyyy'), 6, 1, 'Math');
INSERT INTO PASSING(DATE_EXAM, MARK, STUDENT_NUMBER_OF_BOOK, SUBJECT_NAME) 
    VALUES( to_date('14-03-2018', 'dd-mm-yyyy'), 6, 2, 'Programming');
INSERT INTO PASSING(DATE_EXAM, MARK, STUDENT_NUMBER_OF_BOOK, SUBJECT_NAME) 
    VALUES( to_date('16-03-2018', 'dd-mm-yyyy'), 8, 1, 'Criptography');

--SELECT * FROM PASSING;

INSERT INTO SUBJECT_SEMESTER(SUBJECT_NAME, SEMESTER_NUMBER) VALUES('Criptography', 2);
INSERT INTO SUBJECT_SEMESTER(SUBJECT_NAME, SEMESTER_NUMBER) VALUES('Criptography', 3);
INSERT INTO SUBJECT_SEMESTER(SUBJECT_NAME, SEMESTER_NUMBER) VALUES('Programming', 2);
INSERT INTO SUBJECT_SEMESTER(SUBJECT_NAME, SEMESTER_NUMBER) VALUES('Math', 1);
INSERT INTO SUBJECT_SEMESTER(SUBJECT_NAME, SEMESTER_NUMBER) VALUES('ISO', 2);

--SELECT * FROM SUBJECT_SEMESTER;

INSERT INTO REPORT_SUBJECT(REPORT_NUMBER, SUBJECT_NAME) VALUES(2,'Criptography');
INSERT INTO REPORT_SUBJECT(REPORT_NUMBER, SUBJECT_NAME) VALUES(1,'Programming');
INSERT INTO REPORT_SUBJECT(REPORT_NUMBER, SUBJECT_NAME) VALUES(1,'Math');
INSERT INTO REPORT_SUBJECT(REPORT_NUMBER, SUBJECT_NAME) VALUES(2,'Math');
INSERT INTO REPORT_SUBJECT(REPORT_NUMBER, SUBJECT_NAME) VALUES(3,'ISO');

--SELECT * FROM REPORT_SUBJECT;

