CREATE SEQUENCE PASS_SEQ START WITH 1;

CREATE TABLE PASSING (
    ID                       INTEGER DEFAULT PASS_SEQ.NEXTVAL NOT NULL,
    DATE_EXAM                DATE NOT NULL,
    MARK                     INTEGER NOT NULL,
    STUDENT_NUMBER_OF_BOOK   INTEGER NOT NULL,
    SUBJECT_NAME             VARCHAR2(40) NOT NULL,
    
    CONSTRAINT PASSING_PK PRIMARY KEY ( ID ),
    CONSTRAINT CHECK_MARK CHECK(MARK BETWEEN 2 AND 10)
);

CREATE SEQUENCE STUDENT_SEQ START WITH 1;

CREATE TABLE STUDENT(
    NUMBER_OF_BOOK    INTEGER DEFAULT STUDENT_SEQ.NEXTVAL NOT NULL,
    FIRST_NAME        VARCHAR2(20) NOT NULL,
    LAST_NAME         VARCHAR2(30) NOT NULL,
    SEMESTER_NUMBER   INTEGER NOT NULL,
    
    CONSTRAINT NUMBER_OF_BOOK_PK PRIMARY KEY ( NUMBER_OF_BOOK )
);

CREATE TABLE SEMESTER(
    NUMBER_SEMESTER   INTEGER NOT NULL,
    DESCRIPTION       VARCHAR2(10) NOT NULL,
    
    CONSTRAINT SEMESTER_PK PRIMARY KEY(NUMBER_SEMESTER),
    CONSTRAINT CHECK_NUMBER_SEMESTER CHECK(NUMBER_SEMESTER BETWEEN 1 AND 8)
);

CREATE TABLE SUBJECT(
    NAME    VARCHAR2(40) NOT NULL,
    HOURS   INTEGER NOT NULL,
    
    CONSTRAINT SUBJECT_PK PRIMARY KEY (NAME),
    CONSTRAINT HOURS_CHECK CHECK(HOURS >= 0)
);

CREATE TABLE REPORT(
    NUMBER_REPORT     INTEGER NOT NULL,
    DESCRIPTION      VARCHAR2(15) NOT NULL,  -- ?????/???????/??? ??????????
    
    CONSTRAINT REPORT_PK PRIMARY KEY (NUMBER_REPORT),
    CONSTRAINT NUMBER_REPORT_CHECK CHECK( NUMBER_REPORT BETWEEN 1 AND 3)
);

CREATE TABLE SUBJECT_SEMESTER (
    SUBJECT_NAME      VARCHAR2(40) NOT NULL,
    SEMESTER_NUMBER   INTEGER NOT NULL,
    
    CONSTRAINT SUBJECT_SEMESTER_PK PRIMARY KEY (SUBJECT_NAME, SEMESTER_NUMBER)
);

CREATE TABLE REPORT_SUBJECT (
    REPORT_NUMBER   INTEGER NOT NULL,
    SUBJECT_NAME    VARCHAR2(40) NOT NULL,
    
    CONSTRAINT REPORT_SUBJECT_PK PRIMARY KEY(REPORT_NUMBER, SUBJECT_NAME)
);


ALTER TABLE PASSING
    ADD CONSTRAINT PASSING_STUDENT_FK FOREIGN KEY ( STUDENT_NUMBER_OF_BOOK )
        REFERENCES STUDENT ( NUMBER_OF_BOOK ) ON DELETE CASCADE;

ALTER TABLE PASSING
    ADD CONSTRAINT PASSING_SUBJECT_FK FOREIGN KEY ( SUBJECT_NAME )
        REFERENCES SUBJECT ( NAME ) ON DELETE CASCADE;

ALTER TABLE REPORT_SUBJECT
    ADD CONSTRAINT REPORT_SUBJECT_REPORT_NUMBER_FK FOREIGN KEY ( REPORT_NUMBER )
        REFERENCES REPORT ( NUMBER_REPORT );

ALTER TABLE REPORT_SUBJECT
    ADD CONSTRAINT REPORT_SUBJECT_SUBJECT_NAME_FK FOREIGN KEY ( SUBJECT_NAME )
        REFERENCES SUBJECT ( NAME );

ALTER TABLE STUDENT
    ADD CONSTRAINT STUDENT_SEMESTER_FK FOREIGN KEY ( SEMESTER_NUMBER )
        REFERENCES SEMESTER ( NUMBER_SEMESTER )ON DELETE SET NULL;

ALTER TABLE SUBJECT_SEMESTER
    ADD CONSTRAINT SUBJECT_SEMESTER_SEMESTER_NUMBER_FK FOREIGN KEY (SEMESTER_NUMBER  )
        REFERENCES SEMESTER ( NUMBER_SEMESTER );

ALTER TABLE SUBJECT_SEMESTER
    ADD CONSTRAINT SUBJECT_SEMESTER_SUBJECT_NAME_FK FOREIGN KEY ( SUBJECT_NAME )
        REFERENCES SUBJECT ( NAME );


